# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created: Sun Jun 19 18:51:20 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Faunus(object):
    def setupUi(self, Faunus):
        Faunus.setObjectName("Faunus")
        Faunus.resize(600, 296)
        self.centralWidget = QtWidgets.QWidget(Faunus)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_settings = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_settings.setObjectName("groupBox_settings")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_settings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chb_automail = QtWidgets.QCheckBox(self.groupBox_settings)
        self.chb_automail.setObjectName("chb_automail")
        self.gridLayout_3.addWidget(self.chb_automail, 0, 0, 1, 1)
        self.chb_startup_automail = QtWidgets.QCheckBox(self.groupBox_settings)
        self.chb_startup_automail.setObjectName("chb_startup_automail")
        self.gridLayout_3.addWidget(self.chb_startup_automail, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_settings, 1, 0, 1, 1)
        self.groupBox_pop3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_pop3.setObjectName("groupBox_pop3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_pop3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_pop3)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.lne_pop3_server = QtWidgets.QLineEdit(self.groupBox_pop3)
        self.lne_pop3_server.setFrame(True)
        self.lne_pop3_server.setObjectName("lne_pop3_server")
        self.gridLayout_6.addWidget(self.lne_pop3_server, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_pop3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 0, 1, 1)
        self.lne_pop3_port = QtWidgets.QLineEdit(self.groupBox_pop3)
        self.lne_pop3_port.setObjectName("lne_pop3_port")
        self.gridLayout_6.addWidget(self.lne_pop3_port, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_pop3, 1, 1, 1, 1)
        self.groupBox_imap = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_imap.setObjectName("groupBox_imap")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_imap)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lne_imap_server = QtWidgets.QLineEdit(self.groupBox_imap)
        self.lne_imap_server.setFrame(True)
        self.lne_imap_server.setObjectName("lne_imap_server")
        self.gridLayout_5.addWidget(self.lne_imap_server, 0, 1, 1, 1)
        self.lne_imap_port = QtWidgets.QLineEdit(self.groupBox_imap)
        self.lne_imap_port.setObjectName("lne_imap_port")
        self.gridLayout_5.addWidget(self.lne_imap_port, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_imap)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_imap)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_imap, 0, 1, 1, 1)
        self.btn_save_mail = QtWidgets.QPushButton(self.centralWidget)
        self.btn_save_mail.setObjectName("btn_save_mail")
        self.gridLayout_2.addWidget(self.btn_save_mail, 4, 0, 2, 2)
        self.groupBox_account = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_account.setFlat(False)
        self.groupBox_account.setObjectName("groupBox_account")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_account)
        self.gridLayout.setObjectName("gridLayout")
        self.lne_password = QtWidgets.QLineEdit(self.groupBox_account)
        self.lne_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lne_password.setObjectName("lne_password")
        self.gridLayout.addWidget(self.lne_password, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_account)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.lne_username = QtWidgets.QLineEdit(self.groupBox_account)
        self.lne_username.setObjectName("lne_username")
        self.gridLayout.addWidget(self.lne_username, 0, 2, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.groupBox_account)
        self.label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_account, 0, 0, 1, 1)
        Faunus.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Faunus)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 25))
        self.menuBar.setObjectName("menuBar")
        Faunus.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(Faunus)
        self.statusBar.setObjectName("statusBar")
        Faunus.setStatusBar(self.statusBar)

        self.retranslateUi(Faunus)
        QtCore.QMetaObject.connectSlotsByName(Faunus)

    def retranslateUi(self, Faunus):
        _translate = QtCore.QCoreApplication.translate
        Faunus.setWindowTitle(_translate("Faunus", "Faunus AlphaV0.1"))
        self.groupBox_settings.setTitle(_translate("Faunus", "Settings"))
        self.chb_automail.setText(_translate("Faunus", "Automail Check"))
        self.chb_startup_automail.setText(_translate("Faunus", "Startup Automail"))
        self.groupBox_pop3.setTitle(_translate("Faunus", "Outgoing Settings (POP3)"))
        self.label_4.setText(_translate("Faunus", "POP3 Server"))
        self.lne_pop3_server.setText(_translate("Faunus", "pop3.metu.edu.tr"))
        self.label_3.setText(_translate("Faunus", "POP3 Port"))
        self.lne_pop3_port.setText(_translate("Faunus", "995"))
        self.groupBox_imap.setTitle(_translate("Faunus", "Incoming Settings (IMAP)"))
        self.lne_imap_server.setText(_translate("Faunus", "imap.metu.edu.tr"))
        self.lne_imap_port.setText(_translate("Faunus", "993"))
        self.label_5.setText(_translate("Faunus", "IMAP Port"))
        self.label_6.setText(_translate("Faunus", "IMAP Server"))
        self.btn_save_mail.setText(_translate("Faunus", "Save"))
        self.groupBox_account.setTitle(_translate("Faunus", "Login Mail"))
        self.label_2.setText(_translate("Faunus", "Password"))
        self.label_1.setText(_translate("Faunus", "Username"))

